### ISSUE TITLE
[BUG]: z-scoring imagery also z-scores masks

### ISSUE THREAD

**Issue by jshermeyer** [CosmiQ/solaris#216] opened 2019-07-30 14:15 UTC
_Thank you for helping us improve `solaris`!_

## Summary of the bug
z-scoring the imagery works well but also appears to be z-scoring the masks which causes odd outputs out of the net 

## Steps to reproduce the bug
Please either paste sample code used to generate the buggy behavior below, or provide step-by-step instructions to reproduce the problem.

```
Paste bug-causing code here
```

## Buggy behavior and/or error message
Please describe the buggy behavior and/or paste output here.
```
Paste output here
```

## Expected behavior
Masks don't need to be z-scored

## Environment information
- OS: Linux
- `solaris` version: recent
- python version: 3.7
- version of any relevant dependencies (optional - we may ask for this information later if not provided)

**Comment by nrweir** [comment] 2019-07-30 14:22
See #212 for an example of challenges with this. I think the problem is either in `solaris.utils.io.imread()`'s call to `solaris.utils.io.preprocess_im_arr()`, or possibly in the call to `albumentations`' `Normalize` class during pre-processing for the model. Albumentations indicates that `Normalize` only applies to the image, not the mask, but it's worth double-checking the codebase to be sure.

**Comment by nrweir** [comment] 2019-09-09 19:27
I _think_ this got resolved with #248. We can re-open if not.

**Closed by nrweir** 2019-09-09 19:27 UTC
Labels: Difficulty: Medium, Priority: Critical, Status: In Progress, Type: bug
