### ISSUE TITLE
[BUG]: (Install error in window10)

### ISSUE THREAD

**Issue by wubizhi** [CosmiQ/solaris#344] opened 2020-04-01 00:34 UTC
_Thank you for helping us improve `solaris`!_

## Summary of the bug
I tried to Install solaris step by step in the Installation Instructions.
everything went well before i created the "solaris" env in conda,
but when i tried to run the command"pip install ." or "pip install solaris"
there is some errr.

## Steps to reproduce the bug
when i run "pip install ." in the folder,

>pip install .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing d:\solaris-master
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\solaris\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-f8mjkbhm\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-f8mjkbhm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-f8mjkbhm\pip-egg-info'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-f8mjkbhm\
    Complete output (1 lines):
    GDAL must be installed to use `solaris`. See the documentation for more info. We recommend installing GDAL within a conda environment first, then installing solaris there.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

when i run "pip install solaris"
pip install solaris
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting solaris
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/57/9d/1663c1eda9d2bcf8f18bed1ce34477c15855fa0e591bc70f94233661b7fc/solaris-0.2.1-py3-none-any.whl (10.2 MB)
     |████████████████████████████████| 10.2 MB 598 kB/s
Requirement already satisfied: affine>=2.3.0 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (2.3.0)
Collecting opencv-python>=4.1.0.25
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/5a/af/dabae171f885ec4d9b2fe6aaf74c1d50a8d32106d840b9fb8eb0095a578d/opencv_python-4.2.0.32-cp37-cp37m-win_amd64.whl (33.0 MB)
     |████████████████████████████████| 33.0 MB 726 kB/s
Requirement already satisfied: urllib3>=1.25.7 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (1.25.7)
Requirement already satisfied: pandas>=0.25.3 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (1.0.3)
Requirement already satisfied: torchvision>=0.4.2 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (0.5.0)
Requirement already satisfied: geopandas>=0.6.2 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (0.6.2)
Requirement already satisfied: scikit-image>=0.16.2 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (0.16.2)
Requirement already satisfied: pyyaml==5.2 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (5.2)
Requirement already satisfied: pyproj>=2.1 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (2.6.0)
Requirement already satisfied: rio-cogeo>=1.1.6 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (1.1.6)
Requirement already satisfied: rtree>=0.9.3 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (0.9.4)
Requirement already satisfied: scipy>=1.3.2 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (1.4.1)
Requirement already satisfied: tensorflow==1.13.1 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (1.13.1)
Requirement already satisfied: tqdm>=4.40.0 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (4.44.1)
Requirement already satisfied: requests>=2.22.0 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (2.22.0)
Requirement already satisfied: rasterio>=1.0.23 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (1.1.3)
Requirement already satisfied: matplotlib>=3.1.2 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (3.2.1)
Requirement already satisfied: gdal>=3.0.2 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (3.0.4)
Requirement already satisfied: shapely>=1.6.4 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (1.7.0)
Requirement already satisfied: networkx>=2.4 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (2.4)
Requirement already satisfied: pip>=19.0.3 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (20.0.2)
Requirement already satisfied: albumentations==0.4.3 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (0.4.3)
Requirement already satisfied: numpy>=1.17.3 in c:\programdata\anaconda3\envs\solaris\lib\site-packages (from solaris) (1.17.5)
ERROR: Could not find a version that satisfies the requirement torch==1.3.1 (from solaris) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.3.1 (from solaris)

## Screenshots
![image](https://user-images.githubusercontent.com/7642260/78087227-fb15a100-73f2-11ea-9de9-7b2d2e17dbeb.png)
![image](https://user-images.githubusercontent.com/7642260/78087346-63fd1900-73f3-11ea-8965-f4dd674f1f58.png)

## Environment information
- OS:win10 
- `solaris` version:
- python version:3.7
- version of any relevant dependencies (optional - we may ask for this information later if not provided)
(solaris) D:\solaris-master>conda list
# packages in environment at C:\ProgramData\Anaconda3\envs\solaris:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu
absl-py                   0.9.0            py37hc8dfbb8_1    conda-forge
affine                    2.3.0                      py_0    conda-forge
albumentations            0.4.3                      py_0    conda-forge
astor                     0.7.1                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
blas                      1.0                         mkl
boost-cpp                 1.72.0               h0caebb8_0    conda-forge
boto3                     1.12.32            pyh9f0ad1d_0    conda-forge
botocore                  1.15.32            pyh9f0ad1d_0    conda-forge
bzip2                     1.0.8                hfa6e2cd_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
cffi                      1.14.0           py37ha419a9e_0    conda-forge
cfitsio                   3.470                hfa6e2cd_2    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
click                     7.1.1              pyh8c360ce_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.3.0                      py_0    conda-forge
cryptography              2.8              py37hb32ad35_1    conda-forge
cuda100                   1.0                           0    pytorch
cudatoolkit               10.1.243             h74a9793_0
curl                      7.68.0               h4496350_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py37hfa6e2cd_0    conda-forge
dask-core                 2.13.0                     py_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
docutils                  0.15.2                   py37_0    conda-forge
expat                     2.2.9                he025d50_2    conda-forge
fiona                     1.8.13           py37hb7fdc2d_0    conda-forge
freetype                  2.10.1               ha9979f8_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gast                      0.3.3                      py_0    conda-forge
gdal                      3.0.4                    pypi_0    pypi
geopandas                 0.6.2                      py_0    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
geotiff                   1.5.1                h58edbdd_9    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3          py37hc0c2ac7_1002    conda-forge
grpcio                    1.23.0           py37h3f65fb1_1    conda-forge
h5py                      2.10.0          nompi_py37h422b98e_102    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.5          nompi_ha405e13_1104    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.8.0                      py_0    conda-forge
imgaug                    0.4.0                      py_1    conda-forge
intel-openmp              2019.4                      245
jmespath                  0.9.5                      py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
kealib                    1.4.12               hd6dc3df_0    conda-forge
keras-applications        1.0.8                      py_1    conda-forge
keras-preprocessing       1.1.0                      py_0    conda-forge
kiwisolver                1.1.0            py37heaa310e_1    conda-forge
krb5                      1.16.4               hdd46e55_0    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libcurl                   7.68.0               h4496350_0    conda-forge
libffi                    3.2.1             h6538335_1007    conda-forge
libgdal                   3.0.4                h1d28743_3    conda-forge
libiconv                  1.15              hfa6e2cd_1006    conda-forge
libkml                    1.3.0             h7e985d0_1011    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
liblapacke                3.8.0                    14_mkl    conda-forge
libnetcdf                 4.7.4           nompi_hc957ea6_101    conda-forge
libopencv                 4.2.0                    py37_3    conda-forge
libpng                    1.6.37               hfe6a214_1    conda-forge
libpq                     12.2                 h795e76a_0    conda-forge
libprotobuf               3.11.4               h1a1b453_0    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             4.3.0a            h6fa312b_1037    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp                   1.0.2                hfa6e2cd_5    conda-forge
libxml2                   2.9.10               h9ce36c8_0    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markdown                  3.2.1                      py_0    conda-forge
matplotlib                3.2.1                         0    conda-forge
matplotlib-base           3.2.1            py37h911224e_0    conda-forge
mercantile                1.1.2                      py_0    conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py37hfa6e2cd_0    conda-forge
msys2-conda-epoch         20160418                      1
munch                     2.5.0                      py_0    conda-forge
networkx                  2.4                        py_1    conda-forge
ninja                     1.10.0               h1ad3211_0    conda-forge
numpy                     1.17.5           py37hc71023c_0    conda-forge
olefile                   0.46                       py_0    conda-forge
opencv                    4.2.0                    py37_3    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1e               hfa6e2cd_0    conda-forge
pandas                    1.0.3            py37h9b59f54_0    conda-forge
pcre                      8.44                 h6538335_0    conda-forge
pillow                    7.0.0            py37h91e7a8d_1    conda-forge
pip                       20.0.2                     py_2    conda-forge
poppler                   0.67.0               h1707e21_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 hd6b8478_0    conda-forge
proj                      6.3.1                ha7a8c7b_1    conda-forge
protobuf                  3.11.4           py37he025d50_0    conda-forge
py-opencv                 4.2.0            py37h43977f1_3    conda-forge
pycparser                 2.20                       py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    2.6.0            py37hd99c2f7_0    conda-forge
pyqt                      5.12.3           py37h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyreadline                2.1                   py37_1001    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           h60c2a47_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.4.0           py3.7_cuda101_cudnn7_0    pytorch
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.1.1            py37hc8d92b1_0    conda-forge
pyyaml                    5.2              py37hfa6e2cd_0    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
rasterio                  1.1.3            py37h2617b1b_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
rio-cogeo                 1.1.6                      py_0    conda-forge
rtree                     0.9.4            py37h804a536_1    conda-forge
s3transfer                0.3.3            py37hc8dfbb8_0    conda-forge
scikit-image              0.16.2           py37he350917_0    conda-forge
scipy                     1.4.1            py37h9439919_0
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
shapely                   1.7.0            py37he1cf020_2    conda-forge
six                       1.14.0                     py_1    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
supermercado              0.0.5                      py_0    conda-forge
tbb                       2018.0.5             he980bc4_0    conda-forge
tensorboard               1.13.1                   py37_0    conda-forge
tensorflow                1.13.1               h21ff451_7    conda-forge
tensorflow-base           1.13.1                   py37_7    conda-forge
tensorflow-estimator      1.13.0           py37h39e3cac_0    conda-forge
tensorflow-gpu            1.13.1               h0d30ee6_0
termcolor                 1.1.0                      py_2    conda-forge
tiledb                    1.7.0                hffbbd95_2    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
torchvision               0.5.0                py37_cu101    pytorch
tornado                   6.0.4            py37hfa6e2cd_0    conda-forge
tqdm                      4.44.1             pyh9f0ad1d_0    conda-forge
urllib3                   1.25.7           py37hc8dfbb8_1    conda-forge
vc                        14.1                 h21ff451_1    conda-forge
vs2015_runtime            14.16.27012          hf0eaf9b_0    conda-forge
werkzeug                  1.0.0                      py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
xerces-c                  3.2.2             h6538335_1004    conda-forge
xz                        5.2.4             h2fa13f4_1002    conda-forge
yaml                      0.2.2                hfa6e2cd_1    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.4                hd8a0e53_2    conda-forge

**Comment by nrweir** [comment] 2020-04-01 00:42
Hi @wubizhi - I’ve seen this type of thing before. Two possible causes:

1. Either the conda environment isn’t activated, or
2. For some reason the right pip isn’t being called from the shell, even though the conda environment is activated. Try running ‘which pup’ and make sure it’s the one for the Solaris environment.

**Comment by nrweir** [comment] 2020-04-01 00:48
Oh, it also looks like your pypi mirror doesn’t have the right torch version for some reason. You can change the version to 1.4.0 in your setup.py and it should still work.

**Comment by wubizhi** [comment] 2020-04-01 01:11
hi @nrweir ，
1.i have activated the environment
2.i checked the pip,it was on the conda env "solaris"
![image](https://user-images.githubusercontent.com/7642260/78088971-72016880-73f8-11ea-9117-3f3ec4217ca2.png)
3.after i changed the setup.py file with "torch==1.4.0",and  run "python setup.py install" .there was the warining
![image](https://user-images.githubusercontent.com/7642260/78089034-a83ee800-73f8-11ea-9b01-25d239b33670.png)

but the conda env has installed the GDAL already,is
![image](https://user-images.githubusercontent.com/7642260/78089080-d0c6e200-73f8-11ea-93cb-91f9e8384d58.png)

**Comment by nrweir** [comment] 2020-04-01 01:15
Hmm. I don’t know why you have gdal from pypi instead of conda-forge there - you should be using the one from conda-forge. If I had to guess, I’d bet that’s the problem.

**Comment by wubizhi** [comment] 2020-04-01 01:18
@nrweir
when i run the command
"conda env create -n solaris -f environment-gpu.yml"
 it automate install the GDAL

**Comment by wubizhi** [comment] 2020-04-01 01:19
but it used the one from pypi,not from conda-forge,i don't why

**Comment by nrweir** [comment] 2020-04-01 01:21
But it shouldn’t be installing from pypi. I bet there was some intermediate troubleshooting step where it got changed. I’d recommend removing the environment, re-making it using the environment file, then re-try pip install with the updated version of setup.py. 

Good luck!

**Comment by nrweir** [comment] 2020-04-01 14:40
I'm going to close this since it looks to me to have been caused by something unusual about the user's PyPI mirror or troubleshooting process. Feel free to re-open if there's something solaris-specific that you track down as a causal element.

**Closed by nrweir** 2020-04-01 14:40 UTC
Labels: Status: Review Needed, Type: bug

**Comment by wubizhi** [comment] 2020-04-01 17:42
hi@nrweir,
 after i re-maked the "solaris" by the environment file,the GDAL was create by the "Conda-forge",but the problem is still 
![image](https://user-images.githubusercontent.com/7642260/78168710-01ebf480-7483-11ea-8047-7c0c8e8a1f29.png)

i think this is not the problem of PyPI mirror
![image](https://user-images.githubusercontent.com/7642260/78168850-2e077580-7483-11ea-83b8-30b5aaaac9d9.png)

**Comment by sohilp2** [comment] 2020-07-03 18:28
@wubizhi Facing the same issue. Did you solve it?

**Comment by wubizhi** [comment] 2020-07-04 02:24
no，i transfer it to the UBUNTU finally


 
---Original---

**Comment by Adrianahuante** [comment] 2020-07-29 18:13
Same problem here. @sohilp2 did you solve it?

**Comment by wubizhi** [comment] 2020-07-31 00:47
no.. i use the UBUNTU finally. it was solved then


 
---Original---

**Comment by ralvite** [comment] 2021-06-22 10:56
I adressed the same problem in Windows 10

> (solaris) PS C:\tmp\solaris> python .\setup.py install
GDAL must be installed to use `solaris`. See the documentation for more info. We recommend installing GDAL within a conda environment first, then installing solaris there.

> (solaris) PS C:\tmp\solaris> conda list
gdal                      3.0.3            py37h2fee047_0    conda-forge
